### PR TITLE
Added null check for id in mapped data, updated DataGrid slots with noRowsOverlay in Reliability and Resilience components

### LINKED ISSUE #8: [Priority: High] Implement No Data Handling for Dashboard Tables
Currently, the dashboard tables do not handle cases where there is no data available gracefully. When attempting to fetch data and encountering an empty dataset, the dashboard breaks, failing to display any information to the user. 

**Expected Behavior:**
- When fetching data for a dashboard table, if no data is available, the table should gracefully inform the user that no data is present.
- The dashboard should remain functional even when encountering empty datasets, ensuring a seamless user experience.

**Proposed Solution:**
- Implement a mechanism within the dashboard's table component to detect when no data is returned from the backend.
- Display a visually clear message within the table indicating that no data is available.
- Ensure that this message does not disrupt the overall layout or functionality of the dashboard.

**Steps to Reproduce:**
1. Navigate to the dashboard containing tables.
2. Ensure that there is no data available for the table.
3. Observe the behaviour of the dashboard when attempting to display the empty dataset.

### PR DESCRIPTION
**Pull request by Vanessa-Kris**
fixes #8

### CODE REVIEW

**Comment by PromiseFru** [comment]
Thank you, @Vanessa-Kris! Please use a descriptive title for the pull request (PR) and link the issue you're resolving in the PR description. Refer to the [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more insights:

**Comment by Vanessa-Kris** [comment]
fixes #8

**Comment by Vanessa-Kris** [comment]
@PromiseFru I've made the suggested changes, please review.

**Comment by PromiseFru** [comment]
> fixes #8

Thank you, @Vanessa-Kris! Please place the pull request link keyword in the PR description, i.e., in the very first comment box at the top.

**Review by PromiseFru — APPROVED** [review]
Thank you, @Vanessa-Kris and @mildrette. LGTM!

**Pull request merged**
